/**:
 ros__parameters:
  # Ranges Smoothing Filter Size
  # Dimension: 1 x (2*smoothing_filter_size-1)
  smoothing_filter_size: 1

  # Wall Follow PID controller gains

  # 2.45 radians 140 degrees (-70  >  +70)
  forward_view_angle: 2.0

  #rpilidar front index different than hokuyo
  scanner_forward_offsetangle: 0.0

  disparity_threshold: 0.3
  disparity_filter_size: 3
  disparity_publish: true
  car_width: 0.50

  # Desired Car Velocity based on Error
  error_based_ranges.low: 1.0
  error_based_ranges.medium: 3.0
  error_based_ranges.high: 6.0
  error_based_velocities.low: 2.0
  error_based_velocities.medium: 4.0
  error_based_velocities.high: 6.0
  drive_topic: "drive"
  scan_topic: "scan"
